import { DEFAULT_SHOPIFY_STOREFRONT_TIMEOUT_MS } from '@/api/shopify/request/shopifyRequestObservability'

export const RELATED_PRODUCTS_TOTAL_BUDGET_MS =
  DEFAULT_SHOPIFY_STOREFRONT_TIMEOUT_MS
export const RELATED_PRODUCTS_MIN_RETRY_BUDGET_MS = 500
export const RELATED_PRODUCTS_RETRY_JITTER_MIN_MS = 50
export const RELATED_PRODUCTS_RETRY_JITTER_MAX_MS = 200
export const RELATED_PRODUCTS_RUNTIME_CACHE_TTL_SECONDS = 86_400
export const RELATED_PRODUCTS_RUNTIME_CACHE_TAG = 'related-products'
export const RELATED_PRODUCTS_RUNTIME_CACHE_NAME = 'related-products'
