import assert from 'node:assert/strict'
import test from 'node:test'
import { createElement } from 'react'
import type { ElementType } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { useMDXComponents } from '../../../mdx-components'

test('preserves MDX heading ids generated by rehype-slug', () => {
  const components = useMDXComponents()

  assert.equal(typeof components.h2, 'function')
  const Heading = components.h2 as ElementType

  const html = renderToStaticMarkup(
    createElement(
      Heading,
      { id: 'finn-riktig-storrelse' },
      'Finn riktig størrelse'
    )
  )

  assert.match(html, /<h2[^>]+id="finn-riktig-storrelse"/)
  assert.match(html, />Finn riktig størrelse<\/h2>/)
})

test('exposes reusable semantic MDX layout primitives', () => {
  const components = useMDXComponents()

  assert.equal(typeof components.MdxAction, 'function')
  assert.equal(typeof components.MdxCallout, 'function')
  assert.equal(typeof components.MdxColumns, 'function')
  assert.equal(typeof components.MdxFigure, 'function')
  const Callout = components.MdxCallout as ElementType

  const html = renderToStaticMarkup(
    createElement(
      Callout,
      { title: 'Merk' },
      'Innholdet er kontrollert.'
    )
  )

  assert.match(html, /<aside[^>]+aria-label="Merk"/)
  assert.match(html, /role="note"/)
  assert.match(html, />Innholdet er kontrollert\.</)
})

test('renders accessible tables with responsive containment', () => {
  const components = useMDXComponents()

  assert.equal(typeof components.table, 'function')
  assert.equal(typeof components.th, 'function')
  const Table = components.table as ElementType
  const TableHeading = components.th as ElementType

  const html = renderToStaticMarkup(
    createElement(
      Table,
      null,
      createElement(
        'tbody',
        null,
        createElement(
          'tr',
          null,
          createElement(TableHeading, null, 'Størrelse'),
          createElement('td', null, 'Middels')
        )
      )
    )
  )

  assert.match(html, /overflow-x-auto/)
  assert.match(html, /<th[^>]+scope="col"/)
})
