export const META_CATALOG_ID = '690208780604782'
export const META_CATALOG_APP_ID = '1154247890253046'
export const META_GRAPH_API_VERSION = 'v26.0'
export const META_GRAPH_API_ORIGIN = 'https://graph.facebook.com'

export const META_CATALOG_EXPECTED_OFFER_COUNT = 8
export const META_CATALOG_EXPECTED_PUBLISHED_COUNT = 8
export const META_CATALOG_EXPECTED_DELETE_COUNT = 6
export const META_CATALOG_EXPECTED_PUBLISHED_GROUP_COUNT = 4
